title: Dr. Santhosh Kumar # your name (or website title) here
logo: "images/logo1.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  An aspiring Data scientist trained in radiology. I will be using this website to show my work and finally get into Health data science Masters.
  <br><br>
  This website contains my project details and blog posts.
  <br><br>
  <a href="https://www.linkedin.com/in/skgv1024/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-122823600-1 # your Google Analytics tracking ID here
